In [ ]:
#Project  ATM
 
class ATM:
    def __init__(self):
         self.bal = 600000
         self.a= int(input("enter your deposit money:"))
         self.b = int(input("enter your withdraw money:"))

    def deposit_money(self):
         print("enter your deposit money:",self.a)

    def withdraw_money(self):
            print("enter withdraw money:",self.b)


    def check_balance(self):
         if self.a>0:
              if self.b>0:
                   self.bal= self.bal + self.a - self.b
              else:
                   self.bal = self.bal -self.b
         else:
              self.bal = self.bal+self.a
         print("check balance:",self.bal)


a =ATM()
a.deposit_money()
a.withdraw_money()
a.check_balance()

In [342]:
## matric unit

# class BMICalculator:
#     def __init__(self):
#         self.w = float(input("enter weight in kg:"))
#         self.h = float(input("enter height in cm:"))
#         self.sm= "sm"
#     def height(self):
#           c= self.h / 100
#           self.sm= c*c
#           print("height is in meter",self.sm)
#     def weight(self):
#           print("wight in kg",self.w)
#     def calculate_bmi(self):
#      bmi = self.w / self.sm
#      print("body mass index",bmi)

#      if bmi<16:
#       print("severe thinness",bmi)
#      elif bmi>16 or bmi<17:
#       print("moderate thinness",bmi)
#      elif bmi >17 or bmi<18.5:
#       print("mild thinness",bmi)
#      elif bmi>18.5 or bmi<25 :
#       print("normal",bmi)
#      elif bmi>25 or bmi<30:
#       print("overweight",bmi)
#      elif bmi >30 or bmi<35:
#       print("obese class 1",bmi)
#      elif bmi>35 or bmi<40:
#       print("obsese class 2",bmi)
#      else:
#       print("obsese class 3",bmi)          
# b = BMICalculator()
# b.weight()
# b.height()
b.calculate_bmi()

body mass index 178.57142857142856
moderate thinness 178.57142857142856

In [343]:
import os
import numpy as np
import pandas as pd

In [344]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Documents\data.csv")
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [345]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [346]:
df.head()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [347]:
df.head(7)

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
6,6,6,Dell,Inspiron 3520 D560896WIN9B Laptop,36790,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1

In [348]:
df.tail()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [349]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='str')

In [350]:
df[['ROM']]

       ROM
0    512GB
1    512GB
2    512GB
3    512GB
4    256GB
..     ...
888  512GB
889    1TB
890    1TB
891  512GB
892    1TB

[893 rows x 1 columns]

In [351]:
df[['brand','price']]

      brand   price
0        HP   49900
1        HP   39900
2      Acer   26990
3    Lenovo   59729
4     Apple   69990
..      ...     ...
888    Asus   44990
889    Asus  110000
890    Asus  189990
891    Asus  129990
892    Asus  131990

[893 rows x 2 columns]

In [352]:
df["brand"].unique()

<StringArray>
[       'HP',      'Acer',    'Lenovo',     'Apple',      'Dell',      'Asus',
   'Samsung',   'Ultimus', 'Primebook',       'MSI',   'Infinix',     'Wings',
     'Honor', 'Zebronics',    'Xiaomi',     'iBall',     'Chuwi',    'Realme',
     'Avita',    'Walker',    'Huawei',     'Tecno',  'Gigabyte',      'Vaio',
 'Microsoft',   'Fujitsu',        'LG',   'Ninkear',     'Razer',       'AXL']
Length: 30, dtype: str

In [353]:
df["brand"].nunique()

30

In [354]:
df["brand"].value_counts()

brand
HP           186
Lenovo       169
Asus         157
Dell         107
Acer          84
MSI           65
Samsung       28
Apple         16
Infinix       15
LG             9
Xiaomi         8
Gigabyte       8
Fujitsu        6
Ultimus        4
Zebronics      4
Wings          3
Chuwi          3
Realme         3
Tecno          3
Honor          2
Huawei         2
Microsoft      2
AXL            2
Primebook      1
iBall          1
Avita          1
Walker         1
Vaio           1
Ninkear        1
Razer          1
Name: count, dtype: int64

In [355]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
888    False
889    False
890    False
891    False
892    False
Length: 893, dtype: bool

In [356]:
df.duplicated().sum()

np.int64(0)

In [357]:
df.drop_duplicates()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [358]:
df.drop_duplicates(inplace=True)

In [359]:
df.drop_duplicates().sum()

Unnamed: 0.1                                                    417152
Unnamed: 0                                                      465595
brand                HPHPAcerLenovoAppleAcerDellAcerAsusSamsungLeno...
name                 Victus 15-fb0157AX Gaming Laptop15s-fq5007TU L...
price                                                         71357317
spec_rating                                               61955.470588
processor            5th Gen AMD Ryzen 5 5600H12th Gen Intel Core i...
CPU                  Hexa Core, 12 ThreadsHexa Core (2P + 4E), 8 Th...
Ram                  8GB8GB8GB16GB8GB8GB8GB16GB8GB16GB16GB4GB16GB4G...
Ram_type             DDR4DDR4DDR4LPDDR5DDR4DDR4DDR4DDR5DDR4LPDDR5DD...
ROM                  512GB512GB512GB512GB256GB512GB512GB512GB512GB5...
ROM_type             SSDSSDSSDSSDSSDSSDSSDSSDSSDSSDSSDSSDSSDHard-Di...
GPU                  4GB AMD Radeon RX 6500MIntel UHD GraphicsIntel...
display_size                                                  13550.16
resolution_width                                             1817606.0
resolution_height                                            1087964.0
OS                   Windows 11 OSWindows 11 OSWindows 11 OSWindows...
warranty                                                           964
dtype: object

In [360]:
df.isnull()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
891,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
892,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [361]:
df.isnull().sum()

Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [362]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [363]:
df["warranty"].unique()

array([1, 0, 2, 3])

In [364]:
warranty_dict={
    1 : "one", 0 :"zero", 2:"two",3:"three"
}

In [365]:
df["warranty"]=df["warranty"].map(warranty_dict)
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [366]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    str
dtypes: float64(4), int64(3), str(11)
memory usage: 125.7 KB

In [367]:
# df.drop("price", axis=1,inplace=True)
# df

In [368]:
# df.drop(["ROM","ROM_type"],axis =1,inplace=True)
# df

In [369]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    str
dtypes: float64(4), int64(3), str(11)
memory usage: 125.7 KB

In [370]:
obj_val = df.select_dtypes(include="O")

C:\Users\HP\AppData\Local\Temp\ipykernel_13820\2737773647.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val = df.select_dtypes(include="O")

In [371]:
obj_val

,brand,name,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,OS,warranty
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS,one
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,Windows 11 OS,one
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS,one
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS,one
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS,one
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS,one
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS,one
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one

In [372]:
num_val = df.select_dtypes(exclude="O")

In [373]:
num_val

,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height
0,0,0,49900,73.000000,15.6,1920.0,1080.0
1,1,1,39900,60.000000,15.6,1920.0,1080.0
2,2,2,26990,69.323529,14.0,1920.0,1080.0
3,3,3,59729,66.000000,14.0,2240.0,1400.0
4,4,4,69990,69.323529,13.3,2560.0,1600.0
...,...,...,...,...,...,...,...
888,926,1015,44990,69.323529,15.6,1920.0,1080.0
889,927,1016,110000,71.000000,15.6,2560.0,1440.0
890,928,1017,189990,89.000000,14.0,2560.0,1600.0
891,929,1018,129990,73.000000,15.6,1920.0,1080.0
892,930,1019,131990,84.000000,15.6,1920.0,1080.0

In [374]:
complete_data = pd.concat([obj_val,num_val],axis=1)

In [375]:
complete_data

,brand,name,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,OS,warranty,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS,one,0,0,49900,73.000000,15.6,1920.0,1080.0
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,Windows 11 OS,one,1,1,39900,60.000000,15.6,1920.0,1080.0
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS,one,2,2,26990,69.323529,14.0,1920.0,1080.0
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS,one,3,3,59729,66.000000,14.0,2240.0,1400.0
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,Mac OS,one,4,4,69990,69.323529,13.3,2560.0,1600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS,one,926,1015,44990,69.323529,15.6,1920.0,1080.0
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS,one,927,1016,110000,71.000000,15.6,2560.0,1440.0
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS,one,928,1017,189990,89.000000,14.0,2560.0,1600.0
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one,929,1018,129990,73.000000,15.6,1920.0,1080.0
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one,930,1019,131990,84.000000,15.6,1920.0,1080.0

In [376]:
hp_brand = df[df["brand"]=="HP"]
hp_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
18,19,19,HP,Victus 15-fa0666TX Gaming Laptop,68990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one
23,24,24,HP,15s-fq2510tu Laptop,49580,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",16GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
25,26,26,HP,15s-eq2132AU Laptop,43990,63.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",16GB,DDR4,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,903,992,HP,Victus 15-fb0137AX Gaming Laptop,74990,67.000000,5th Gen AMD Ryzen 7 5800H,"Octa Core, 16 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one
867,905,994,HP,ProBook 445 G8 7K2J8PA Business Laptop,46490,63.000000,5th Gen AMD Ryzen 7 5800U,"Octa Core, 16 Threads",8GB,DDR4,512GB,SSD,AMD Radeon,14.0,1920.0,1080.0,DOS OS,one
872,910,999,HP,Victus 15-fb0131AX Gaming Laptop,51990,65.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 5600M,15.6,1920.0,1080.0,Windows 11 OS,one
876,914,1003,HP,15s-fq3071TU Laptop,28490,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD Graphics,15.0,1366.0,768.0,Windows 11 OS,one
880,918,1007,HP,Victus 15-fb0135AX Gaming Laptop,59990,64.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one

In [377]:
hp_brand["price"].unique()

array([ 49900,  39900,  68990,  49580,  43990,  19850,  53790,  71990,
        59990,  36490,  70590,  37999,  58990,  51780, 109990,  39150,
        80990,  55850, 139234,  42990,  72999, 126742,  98174,  41950,
        54990,  62990,  69501,  49990,  72990,  69490,  51499,  23990,
        79990,  85999,  52990,  75533,  37990,  32790,  77889,  51990,
        91990,  42200,  41990,  64990,  38999,  60990,  55500, 124999,
       104990,  36999,  51999,  38990,  69990,  76900,  27890,  24999,
        33999,  47990,  31890, 125990,  99999, 107763,  80490,  48999,
       116990,  65600,  61990,  46490,  90490,  55990,  57990,  34250,
        33990,  42999,  38861,  15990,  34999,  82799,  34499,  33800,
        77990,  56990,  83249,  85490,  66648,  63490,  57580,  35999,
        41710,  45890,  29990,  37672,  67990,  83149,  54999,  51573,
        32990,  37290,  90464, 121900,  50490, 362999, 169999, 189999,
       298999, 267999,  26990,  89999, 123300,  91590, 103060,  39600,
       415000,  50990,  64800,  42900, 179490,  69199, 116463, 153625,
       270129, 107190, 102090, 231746, 146599, 128599, 151990,  22990,
        29999,  97705, 240707, 234990, 209990, 390914, 172588, 254657,
        26999, 103099,  94990,  86490,  77490,  34990,  44990, 115990,
       137890,  46990,  66500, 171499,  74990,  28490])

In [378]:
# p_price = hp_brand[hp_brand['price']<100000]
# hp_phrice

In [379]:
hp_warranety= hp_brand[hp_brand['warranty']=="three"]
hp_warranety

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
481,503,570,HP,EliteBook 840 G6,90464,69.323529,8th Gen Intel Core i5 8265U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Integrated UHD Graphics 620,14.0,1920.0,1080.0,Windows 10 OS,three

In [380]:
df.drop_duplicates()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [381]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='str')

In [382]:
df_gb = hp_brand[hp_brand["ROM"]<"16gb"]
df_gb

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
136,140,154,HP,Chromebook 15a-na0012TU Laptop,23990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",4GB,LPDDR4x,128GB,Hard-Disk,Intel Integrated UHD Graphics,15.6,1366.0,768.0,Chrome OS,one
351,370,411,HP,Chromebook 15a-na0012TU Laptop,15990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",4GB,LPDDR4x,128GB,Hard-Disk,Intel Integrated UHD Graphics,15.6,1366.0,768.0,Chrome OS,one

In [383]:
acer_brand = df[df["brand"]=="Acer"]
acer_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
7,7,7,Acer,Nitro V ANV15-51 2023 Gaming Laptop,76990,63.000000,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
22,23,23,Acer,Aspire 7 A715-76G UN.QMYSI.002 Gaming Laptop,54990,72.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
27,28,29,Acer,Extensa 15 EX215-33 2023 Laptop,28990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,one
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,one
881,919,1008,Acer,Swift Edge 16 2023 Laptop,107399,69.323529,7th Gen AMD Ryzen 7040 Series 040,"Octa Core, 16 Threads",16GB,LPDDR5,1TB,SSD,AMD Radeon AMD,16.0,3840.0,2400.0,Windows 11 OS,one
886,924,1013,Acer,Aspire Vero AV14-52P NX.KJTSI.002 Laptop,49990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",16GB,LPDDR4X,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,one
887,925,1014,Acer,Aspire 5 A515-58M NX.KHGSI.002 Gaming Laptop,56990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one

In [384]:
acer_ram= acer_brand[acer_brand["Ram"]<"128GB"]
acer_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
7,7,7,Acer,Nitro V ANV15-51 2023 Gaming Laptop,76990,63.000000,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
22,23,23,Acer,Aspire 7 A715-76G UN.QMYSI.002 Gaming Laptop,54990,72.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
27,28,29,Acer,Extensa 15 EX215-33 2023 Laptop,28990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,one
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,one
881,919,1008,Acer,Swift Edge 16 2023 Laptop,107399,69.323529,7th Gen AMD Ryzen 7040 Series 040,"Octa Core, 16 Threads",16GB,LPDDR5,1TB,SSD,AMD Radeon AMD,16.0,3840.0,2400.0,Windows 11 OS,one
886,924,1013,Acer,Aspire Vero AV14-52P NX.KJTSI.002 Laptop,49990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",16GB,LPDDR4X,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,one
887,925,1014,Acer,Aspire 5 A515-58M NX.KHGSI.002 Gaming Laptop,56990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one

In [385]:
acer_rom = acer_brand[acer_brand["ROM_type"]=="SSD"]
acer_rom

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
7,7,7,Acer,Nitro V ANV15-51 2023 Gaming Laptop,76990,63.000000,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
22,23,23,Acer,Aspire 7 A715-76G UN.QMYSI.002 Gaming Laptop,54990,72.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
27,28,29,Acer,Extensa 15 EX215-33 2023 Laptop,28990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,one
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,one
881,919,1008,Acer,Swift Edge 16 2023 Laptop,107399,69.323529,7th Gen AMD Ryzen 7040 Series 040,"Octa Core, 16 Threads",16GB,LPDDR5,1TB,SSD,AMD Radeon AMD,16.0,3840.0,2400.0,Windows 11 OS,one
886,924,1013,Acer,Aspire Vero AV14-52P NX.KJTSI.002 Laptop,49990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",16GB,LPDDR4X,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,one
887,925,1014,Acer,Aspire 5 A515-58M NX.KHGSI.002 Gaming Laptop,56990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one

In [388]:
df[(df["brand"]=="Apple")  & (df["price"]<200000)  &  (df["processor"]=="Apple M2") ]

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one

In [390]:
df.query("brand=='Asus' and price<100000 and Ram =='8GB' ")

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
8,8,8,Asus,Vivobook 15 X1502ZA-EJ523WS Laptop,48990,64.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one
15,16,16,Asus,TUF Gaming F15 FX506HF-HN024W Gaming Laptop,53649,70.000000,11th Gen Intel Core i5 11400H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
20,21,21,Asus,Vivobook 16X 2022 M1603QA-MB502WS Laptop,49900,65.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Vega 7,16.0,1920.0,1200.0,Windows 11 OS,one
89,91,94,Asus,VivoBook 14 X415EA-EK326WS Notebook,30990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated Intel UHD,14.0,1920.0,1080.0,Windows 11 OS,one
102,104,107,Asus,VivoBook 15 X515EA-EJ522WS Laptop,38990,60.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one
106,109,112,Asus,Vivobook 15 X1502ZA-EJ385WS Laptop,40990,69.323529,12th Gen Intel Core i3 1220P,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
132,136,150,Asus,Vivobook 15 X1502ZA-EJ532WS Laptop,46999,64.000000,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one
154,160,180,Asus,Vivobook Pro 15 M6500QF-HN521WS Laptop,59990,60.000000,5th Gen AMD Ryzen 5 5600HS,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
156,162,182,Asus,VivoBook 14 X415EA-EK326WS Notebook,33990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated Intel UHD,14.0,1920.0,1080.0,Windows 11 OS,one
174,180,203,Asus,Vivobook 15 X1502ZA-EJ953WS Laptop,39990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,one
205,211,239,Asus,Vivobook 15 Touch X515EA-EZ311WS Laptop,38990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
257,273,306,Asus,VivoBook 15 X1500EA-EJ311W Laptop,31990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,one
267,283,318,Asus,TUF Gaming F15 FX506HF-HN075W Gaming Laptop,53990,66.000000,11th Gen Intel Core i5 11260H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
279,295,331,Asus,Vivobook 15 X1504ZA-NJ325WS Laptop,40990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
281,298,334,Asus,VivoBook 15 X1500EA-EJ326WS Laptop,37990,69.323529,11th Gen intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
286,303,339,Asus,Vivobook 15 X1504ZA-NJ321WS Laptop,37980,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
307,326,365,Asus,Vivobook 15 X1504ZA-NJ521WS Laptop,45990,69.323529,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Integrated Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
325,344,384,Asus,TUF Gaming F17 FX706HF-HX018W Laptop,53990,64.000000,11th Gen Intel Core i5 11400H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,17.3,1920.0,1080.0,Windows 11 OS,one
352,371,412,Asus,Vivobook Go 14 2023 E1404FA-NK322WS Laptop,33980,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
359,378,419,Asus,Vivobook Go 15 OLED 2023 E1504FA-LK521WS Laptop,50990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,one
384,404,449,Asus,VivoBook 14 X1400EA-EK322WS Notebook,31990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated Intel UHD,14.0,1920.0,1080.0,Windows 11 OS,one
394,414,466,Asus,Vivobook Go 14 2023 E1404FA-NK322WS Laptop,33199,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
399,419,471,Asus,Vivobook Go 15 2023 E1504FA-NJ522WS Laptop,44990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,one
410,430,489,Asus,VivoBook 15 X1500EA-EJ3381WS Laptop,34990,69.323529,11th Gen intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
415,435,498,Asus,Vivobook 15 X1502ZA-EJ381WS Laptop,40689,69.323529,12th Gen Intel Core i3 1220P,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
426,446,510,Asus,VivoBook 14 2022 X1402ZA-MW311WS Laptop,49990,62.000000,12th Gen Intel Core i3 1220P,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows 11 OS,one
427,447,511,Asus,VivoBook 14 2022 X1402ZA-EK521WS Laptop,54990,62.000000,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows 11 OS,one
435,455,519,Asus,VivoBook 14 X415EA-EK322WS Notebook,37990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated Intel UHD,14.0,1920.0,1080.0,Windows 11 OS,one
439,460,524,Asus,VivoBook 15 X1500EA-EJ322WS Laptop,33990,69.323529,11th Gen intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
457,478,542,Asus,TUF Gaming F15 FX506LHB-HN355WS Gaming Laptop,51990,62.000000,10th Gen Intel Core i5 10300H,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,one
490,514,582,Asus,TUF Gaming F15 FX506LHB-HN355WS Gaming Laptop,52990,62.000000,10th Gen Intel Core i5 10300H,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,one
523,547,625,Asus,Vivobook Go 14 E1404FA-NK547WS Laptop,43990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
537,561,641,Asus,Vivobook Go 14 E410KA-EK013W Laptop,23990,69.323529,Intel N4500,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,one
606,635,717,Asus,VivoBook 15 X515MA-BR022WS Laptop,28099,69.323529,Intel Celeron N4020,"Dual Core, 2 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD 600,15.6,1366.0,768.0,Windows OS,one
653,685,767,Asus,Vivobook Go 14 2023 E1404FA-NK327WS Laptop,33990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
662,694,776,Asus,Vivobook Go 14 2023 E1404FA-NK325WS Laptop,33990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
782,820,905,Asus,TUF Gaming F15 FX506HF-HN026W Gaming Laptop,58990,71.000000,11th Gen Intel Core i5 11400H,"Hexa Core, 12 Threads",8GB,DDR4,1TB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,one
813,851,938,Asus,Vivobook 15 X1504ZA-NJ521WS Laptop,47890,69.323529,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Integrated Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
866,904,993,Asus,Eeebook 15 E510MA-EJ011WS Laptop,25990,69.323529,Intel Celeron N4020,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel UHD Integrated,15.6,1920.0,1080.0,Windows 11 OS,one
873,911,1000,Asus,Vivobook 16 2023 M1605YA-MB521WS Laptop,47990,63.000000,7th Gen AMD Ryzen 5 7530U,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Radeon AMD,16.0,1920.0,1200.0,Windows 11 OS,one
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one

In [391]:
x = df.drop("price",axis = 1)
x

,Unnamed: 0.1,Unnamed: 0,brand,name,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [392]:
y = df[["price"]]
y

      price
0     49900
1     39900
2     26990
3     59729
4     69990
..      ...
888   44990
889  110000
890  189990
891  129990
892  131990

[893 rows x 1 columns]

In [ ]:
# y = mx+c

# #this is liner regression equation
# where
# m =slope
# c = intersect
# y = df[["price"]]
# x = df.drop("price",axis = 1)
    
# here y is dependent on x when x value increase then 
# y also increase

 y = mx+c

#### #this is liner regression equation
##### where
##### m =slope
##### c = intersect
#### y = df[["price"]]
##### x = df.drop("price",axis = 1)
    
#### here y is dependent on x when x value increase then 
##### y also increase