In [270]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\onedrive\desktop\data science\data\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\onedrive\desktop\data science\data\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\onedrive\desktop\data science\data\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\onedrive\desktop\data science\data\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\onedrive\desktop\data science\data\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

What is Pandas?

Pandas is a powerful Python library used for:

Data analysis
Data manipulation
Data cleaning
Working with tables and spreadsheets

It is mainly used in:

Data Science
Machine Learning
Data Analytics

Pandas provides fast and flexible data structures for handling structured data.



| Feature            | Description                              |
| ------------------ | ---------------------------------------- |
| Fast and Efficient | Handles large datasets quickly           |
| Easy Data Handling | Simple syntax for manipulating data      |
| File Support       | Works with CSV, Excel, JSON, SQL, etc.   |
| Data Cleaning      | Handles missing or duplicate data        |
| Powerful Analysis  | Supports grouping, filtering, statistics |






| Function     | Purpose                   |
| ------------ | ------------------------- |
| `head()`     | Shows first 5 rows        |
| `tail()`     | Shows last 5 rows         |
| `info()`     | Gives dataset information |
| `describe()` | Statistical summary       |
| `shape`      | Returns rows and columns  |
| `columns`    | Shows column names        |
| `dtypes`     | Shows data types          |

In [271]:
import os
import numpy as np
import pandas as pd

In [272]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Documents\Used_Bikes.csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [273]:
df.head()       #bydefault give 5 row

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [274]:
df.head(10)   #give

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [275]:
df.tail()      # bydefault give last 5 row return

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [276]:
df.info()  # give information of data set

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [277]:
df.columns        #no bracket  give column in data

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [278]:
df["brand"]   #for partucular colunm

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [279]:
df[["brand"]]    #using by 2 squrae bracket dta will be in format

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [280]:
df[["brand","price"]]         #for more than one column use comm betwen t

               brand     price
0                TVS   35000.0
1      Royal Enfield  119900.0
2            Triumph  600000.0
3                TVS   65000.0
4             Yamaha   80000.0
...              ...       ...
32643           Hero   39000.0
32644            TVS   30000.0
32645          Bajaj   60000.0
32646           Hero   15600.0
32647          Bajaj   22000.0

[32648 rows x 2 columns]

In [281]:
df["brand"].unique()      #unique name of brand

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [282]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [283]:
df["brand"].nunique()     #no of unique value of brand

23

In [284]:
df["brand"].value_counts()    ### ek data k kitne item available h

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [285]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [286]:
df.duplicated().sum() #number of duplicated values

np.int64(25324)

In [287]:
df.drop_duplicates()  #it will be remove dupicaten value

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
df.duplicated().sum() #drop kren k bad bhi duplicate hategi but permanently remove hi hogi

np.int64(25324)

In [289]:
df.drop_duplicates(inplace=True)   # this will be remove permanently duplicate value

In [290]:
df.duplicated().sum()  #

np.int64(0)

In [291]:
df.isnull()  #check null values present in the data

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [292]:
df.isnull().sum()   # 0 means no null value

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [293]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [294]:
#y = mx+c

df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [295]:
# owner_dict = {
# 'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4

# }              #####string change into integer

In [296]:
# df["owner"]=df["owner"].map(owner_dict) 
# df

In [297]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [298]:
# df.drop('city',axis=1,inplace=True)  #drop krne p vo coulnm gayab ho jayegga
# df

In [299]:
#df

In [300]:
#df.drop(["price","bike_name"],axis=1,inplace=True)

In [301]:
#df

In [302]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [303]:
obj_val =df.select_dtypes(include="O")   ## here o is object data type 
                                            ##pandas uses O  ass a shortcut for a column
                                            # that contain string/text data

C:\Users\HP\AppData\Local\Temp\ipykernel_8256\4021565837.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val =df.select_dtypes(include="O")   ## here o is object data type

In [304]:
obj_val

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [305]:
num_val = df.select_dtypes(exclude="O")

In [306]:
num_val

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [307]:
complete_Data = pd.concat([obj_val,num_val],axis=1) # isme include o and exclude
                                                     #o ko ek sathn combine kr diya

In [308]:
complete_Data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000.0,7127.0,5.0,220.0

# filtering

In [309]:
tvs_brand = df[df["brand"]=="TVS"]    # jb sirf ek hi brand chaye ho

In [310]:
tvs_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [311]:
tvs_brand["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner']
Length: 3, dtype: str

In [312]:
tvs_first= tvs_brand[tvs_brand['owner']=='First Owner']
tvs_first

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [313]:
tvs_age=tvs_first[tvs_first["age"]<=2]
tvs_age

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [314]:
#   1 . drop dupli value
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [315]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [316]:


df['age'].unique()

array([ 3.,  4.,  8.,  6.,  7.,  5.,  2., 16., 13.,  9., 10., 14., 12.,
       11.,  1., 15., 39., 17., 18., 30., 19., 23., 41., 27., 37., 24.,
       20., 43., 38., 63., 34., 31., 22., 26., 25.])

In [317]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [318]:
# #age_dict ={
#         3:"3",  4:"4",  8:"8",  6:"6", 7:"7",  5:"5",  2:"2", 16:"16", 13:"13",  9:"9", 10:"10", 14:"14", 12:"12",
#        11:"11",  1:"1", 15:"15", 39:"39", 17:"17", 18:"18", 30:'30', 19:"19", 23:"23", 41:"41", 27:"27", 37:"37", 24:"24",
#        20:"20", 43:"43", 38:"38", 63:"63", 34:"34", 31:"31", 22:"21", 26:"26", 25:"25"
# }

In [319]:
#df["age"]=df["age"].map(age_dict)

In [320]:
#df

In [321]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [322]:
tvs_km= tvs_age[tvs_age["kms_driven"]<=20000]

In [323]:
tvs_km

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [324]:
royal_enfield = df[df["brand"]=='Royal Enfield']

In [325]:
royal_enfield

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,First Owner,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,First Owner,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield

In [326]:
royal_enfield['age'].unique()

array([ 4.,  3.,  7.,  5.,  2.,  8., 13.,  6., 10., 11.,  9., 39., 16.,
       14., 12., 15., 17., 18., 27., 37., 20., 43., 19., 38., 63., 24.,
       34., 31., 22., 26.])

In [327]:
#age less than 2
royal_age= royal_enfield[royal_enfield['age']<=2]

In [328]:
royal_age

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [329]:
royal_km=royal_age[royal_age['kms_driven']<=50000]

In [330]:
royal_km

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [331]:
royal3=royal_enfield[royal_enfield['owner']=='Third Owner']

In [332]:
royal3

,bike_name,price,city,kms_driven,owner,age,power,brand
766,Royal Enfield Bullet Electra Twinspark 350cc,85000.0,Palwal,23399.0,Third Owner,6.0,350.0,Royal Enfield
1225,Royal Enfield Thunderbird 500cc,119000.0,Bangalore,11976.0,Third Owner,6.0,500.0,Royal Enfield
2796,Royal Enfield Thunderbird 500cc,95000.0,Ahmedabad,30000.0,Third Owner,8.0,500.0,Royal Enfield
2978,Royal Enfield‎ Bullet 350cc,95000.0,Bangalore,50000.0,Third Owner,43.0,350.0,Royal Enfield
4681,Royal Enfield Thunderbird 350cc,75000.0,Bardhaman,22000.0,Third Owner,10.0,350.0,Royal Enfield
5790,Royal Enfield Bullet Electra 350cc,55000.0,Delhi,4572.0,Third Owner,17.0,350.0,Royal Enfield
5918,Royal Enfield Thunderbird 350cc,45000.0,Bangalore,93108.0,Third Owner,18.0,350.0,Royal Enfield
6282,Royal Enfield Bullet Electra 350cc,60000.0,Delhi,36000.0,Third Owner,11.0,350.0,Royal Enfield
6685,Royal Enfield‎ Bullet 350cc,120000.0,Bangalore,8000.0,Third Owner,38.0,350.0,Royal Enfield
7860,Royal Enfield‎ Bullet 350cc,65000.0,Gurgaon,14101.0,Third Owner,34.0,350.0,Royal Enfield
8190,Royal Enfield Bullet Electra 350cc,85000.0,Bundi,15000.0,Third Owner,7.0,350.0,Royal Enfield
8396,Royal Enfield Classic 500cc,150000.0,Mathura,17000.0,Third Owner,4.0,500.0,Royal Enfield
8676,Royal Enfield Classic Desert Storm 500cc,92000.0,Ludhiana,23569.0,Third Owner,7.0,500.0,Royal Enfield
9183,Royal Enfield Thunderbird 350cc,35800.0,Bangalore,90408.0,Third Owner,18.0,350.0,Royal Enfield

In [333]:
royal_price=royal_enfield[royal_enfield['price']<=150000]

In [334]:
royal_price

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,First Owner,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,First Owner,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield

In [335]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [336]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<150000) ]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [337]:
# qurey is used to extract information 
df.query("brand=='Royal Enfield' and age<=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [338]:
df.drop('bike_name',axis=1,inplace=True)

In [ ]:
df.drop('price',axis=1)

In [340]:
x = df.drop('price',axis=1)

In [342]:
y = df[['price']]

In [343]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [ ]:
x   ##### when x value is increasing then dependent value of y also increase

           city  kms_driven        owner  age  power            brand
0     Ahmedabad     17654.0  First Owner  3.0  110.0              TVS
1         Delhi     11000.0  First Owner  4.0  350.0    Royal Enfield
2         Delhi       110.0  First Owner  8.0  675.0          Triumph
3     Bangalore     16329.0  First Owner  4.0  180.0              TVS
4     Bangalore     10000.0  First Owner  3.0  150.0           Yamaha
...         ...         ...          ...  ...    ...              ...
9362      Delhi     48587.0  First Owner  8.0  150.0             Hero
9369  Bangalore     60000.0  First Owner  9.0  220.0            Bajaj
9370    Jodhpur      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0  First Owner  4.0  400.0            Bajaj
9372  Hyderabad      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [ ]:
df.to_csv("clean_bike_data.csv") ####way of cleaning data